# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:08 +0200
EAPI=8

inherit octave

DESCRIPTION="Geometry toolbox for 2D/3D geometric computing."
LICENSE="BSD-2-Clause-FreeBSD"
HOMEPAGE="https://sourceforge.net/p/octave/matgeom/ci/master/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/matgeom-1.2.2.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.2.0"
DEPEND="${RDEPEND}"
