# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:46 +0200
EAPI=8

inherit octave

DESCRIPTION="Additional functions for manipulation and analysis of strings."
LICENSE="GPL-3.0-or-later FreeBSD"
HOMEPAGE="https://sourceforge.net/p/octave/strings/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/strings-1.2.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.8.0"
DEPEND="${RDEPEND}"
