# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:28 +0200
EAPI=8

inherit octave

DESCRIPTION="General tools for Octave."
LICENSE="GPL-3.0-or-later BSD-3-Clause public-domain"
HOMEPAGE="https://sourceforge.net/p/octave/general/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/general-2.1.1.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
