# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:14 +0200
EAPI=8

inherit octave

DESCRIPTION="A Drift-Diffusion simulator for 2d semiconductor devices."
LICENSE="GPL-2.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave-cfitsio/code/ci/default/tree"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/secs2d-0.0.8.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-2.9.17"
DEPEND="${RDEPEND}"
