# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:17 +0200
EAPI=8

inherit octave

DESCRIPTION="Use FEM for solving boundary value problems in two space dimensions."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/AndreasStahel/FEMoctave/"

SRC_URI="
https://github.com/AndreasStahel/FEMoctave/archive/v2.0.3.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-5.2.0"
DEPEND="${RDEPEND}"
