# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:01 +0200
EAPI=8

inherit octave

DESCRIPTION="A toolbox for internal fluid flow for GNU Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave/"

SRC_URI="
	https://github.com/aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave/archive/refs/tags/v0.0.1.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
