# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:20 +0200
EAPI=8

inherit octave

DESCRIPTION="This package allows to do boolean operations with polygons using the Greiner-Hormann algorithm"
LICENSE="GPL-3.0-or-later BSD-3-Clause"
HOMEPAGE="https://bitbucket.org/jgpallero/octclip/src/master/"

SRC_URI="
	https://bitbucket.org/jgpallero/octclip/downloads/octclip-2.0.3.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.6.0"
DEPEND="${RDEPEND}"
