# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:53 +0200
EAPI=8

inherit octave

DESCRIPTION="Common Gateway Interface for Octave."
LICENSE="GPL-2.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/cgi/ci/master/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/cgi-0.1.2.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.8.0"
DEPEND="${RDEPEND}"
