# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:05 +0200
EAPI=8

inherit octave

DESCRIPTION="Octave bindings to the GNU Scientific Library."
LICENSE="GPL-2.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/gsl/ci/default/tree/"

SRC_URI="
https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/gsl-2.1.1.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-2.9.7"
DEPEND="${RDEPEND}"
