# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:01 +0200
EAPI=8

inherit octave

DESCRIPTION="Octave bindings to the GNU Scientific Library."
LICENSE="GPL-2.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/gsl/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/gsl-2.1.1.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-2.9.7"
DEPEND="${RDEPEND}"
