# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:21:15 +0200
EAPI=8

inherit octave

DESCRIPTION="Basic Octave implementation of mqtt toolkit"
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave-mqtt/code/ci/default/tree"

SRC_URI="
https://downloads.sourceforge.net/project/octave-mqtt/v0.0.1/octave-mqtt-0.0.1.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	dev-python/paho-mqtt
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
