# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:50 +0200
EAPI=8

inherit octave

DESCRIPTION="Data manipulation toolbox similar to R data.frame."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/dataframe/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/dataframe-1.2.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.4.0"
DEPEND="${RDEPEND}"
