# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:12 +0200
EAPI=8

inherit octave

DESCRIPTION="A Drift-Diffusion simulator for 1d semiconductor devices."
LICENSE="GPL-2.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/control/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/secs1d-0.0.9.tar.gz -> ${P}.tar.gz"
RDEPEND="
	octave-packages/bim
	>=sci-mathematics/octave-3.0.0"
DEPEND="${RDEPEND}"
