# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:16 +0200
EAPI=8

inherit octave

DESCRIPTION="Interface to VIBes, Visualizer for Intervals and Boxes."
LICENSE="GPL-3.0-or-later MIT"
HOMEPAGE="https://sourceforge.net/p/octave/vibes/ci/octave-api/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/vibes-0.2.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
