# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:06 +0200
EAPI=8

inherit octave

DESCRIPTION="Additional spline functions"
LICENSE="GPL-3.0-or-later public-domain"
HOMEPAGE="https://sourceforge.net/p/octave/splines/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/splines-1.3.3.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.6.0"
DEPEND="${RDEPEND}"
