# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:24 +0200
EAPI=8

inherit octave

DESCRIPTION="Automatic-Differentiation for Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/StevenWaldrip/Automatic-Differentiation"

SRC_URI="
	https://github.com/StevenWaldrip/Automatic-Differentiation/archive/refs/tags/1.0.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-5.1.0"
DEPEND="${RDEPEND}"
