# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:54 +0200
EAPI=8

inherit octave

DESCRIPTION="Automatic-Differentiation for Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/StevenWaldrip/Automatic-Differentiation"

SRC_URI="
https://github.com/StevenWaldrip/Automatic-Differentiation/archive/refs/tags/1.0.0.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-5.1.0"
DEPEND="${RDEPEND}"
