# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:13 +0200
EAPI=8

inherit octave

DESCRIPTION="Provides COM interface and additional functionality on Windows."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/windows/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/windows-1.5.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.6.0"
DEPEND="${RDEPEND}"
