# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:16 +0200
EAPI=8

inherit octave

DESCRIPTION="This package allows to call functions of PROJ library for cartographic projections and CRS transformations."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://bitbucket.org/jgpallero/octproj/src/master/"

SRC_URI="
	https://bitbucket.org/jgpallero/octproj/downloads/octproj-3.0.2.tar.gz -> ${P}.tar.gz"
RDEPEND="
	sci-libs/proj
	>=sci-mathematics/octave-3.0.0"
DEPEND="${RDEPEND}"
