# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:53 +0200
EAPI=8

inherit octave

DESCRIPTION="A statistics and machine learning toolbox for data with and w/o missing values."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/NaN/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/nan-3.5.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.8.0"
DEPEND="${RDEPEND}"
