# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:56 +0200
EAPI=8

inherit octave

DESCRIPTION="The Statistics package for GNU Octave."
LICENSE="GPL-3.0-or-later public-domain"
HOMEPAGE="https://github.com/gnu-octave/statistics/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/statistics-1.4.2.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=octave-packages/io-1.0.18
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
