# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:21:05 +0200
EAPI=8

inherit octave

DESCRIPTION="Basic Octave implementation of the sqlite toolkit"
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/gnu-octave/octave-sqlite/"

SRC_URI="
https://github.com/gnu-octave/octave-sqlite/releases/download/v0.0.1/octave-sqlite-0.0.1.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	dev-db/sqlite
	>=sci-mathematics/octave-6.0.0"
DEPEND="${RDEPEND}"
