# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:51 +0200
EAPI=8

inherit octave

DESCRIPTION="Input/Output in external formats."
LICENSE="GPL-3.0-or-later BSD-2-Clause"
HOMEPAGE="https://sourceforge.net/p/octave/io/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/io-2.6.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.2.0"
DEPEND="${RDEPEND}"
