# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:00 +0200
EAPI=8

inherit octave

DESCRIPTION="A toolbox for the Ponchón-Savarit method for GNU Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/aumpierre-unb/Ponchon-Savarit-for-GNU-Octave/"

SRC_URI="
https://github.com/aumpierre-unb/Ponchon-Savarit-for-GNU-Octave/archive/refs/tags/v0.1.0.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
