# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:11 +0200
EAPI=8

inherit octave

DESCRIPTION="Multivariate normal distribution clustering and utility functions."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/mvn/ci/default/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/mvn-1.1.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.6.0"
DEPEND="${RDEPEND}"
