# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:56 +0200
EAPI=8

inherit octave

DESCRIPTION="Functional Data Analysis."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://gitlab.com/kakila/fda"

SRC_URI="
https://gitlab.com/kakila/fda/-/archive/master/fda-master.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-4.2.0"
DEPEND="${RDEPEND}"
