# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:24 +0200
EAPI=8

inherit octave

DESCRIPTION="Functional Data Analysis."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://gitlab.com/kakila/fda"

SRC_URI="
	https://gitlab.com/kakila/fda/-/archive/master/fda-master.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.2.0"
DEPEND="${RDEPEND}"
