# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:18 +0200
EAPI=8

inherit octave

DESCRIPTION="Octave bindings for basic Message Passing Interface (MPI) functions for parallel computing."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/carlodefalco/octave-mpi/"

SRC_URI="
	https://github.com/carlodefalco/octave-mpi/releases/download/v3.1.0/mpi-3.1.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-4.4.0"
DEPEND="${RDEPEND}"
