# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:44 +0200
EAPI=8

inherit octave

DESCRIPTION="Octave bindings for basic Message Passing Interface (MPI) functions for parallel computing."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/carlodefalco/octave-mpi/"

SRC_URI="
https://github.com/carlodefalco/octave-mpi/releases/download/v3.1.0/mpi-3.1.0.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-4.4.0"
DEPEND="${RDEPEND}"
