# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:57 +0200
EAPI=8

inherit octave

DESCRIPTION="JSON support by Matlab compatible (jsondecode / jsonencode) functions."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/gnu-octave/pkg-json/"

SRC_URI="
	https://github.com/gnu-octave/pkg-json/archive/v1.0.0.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-5.1.0
	<sci-mathematics/octave-7.0.0"
DEPEND="${RDEPEND}"
