# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:21:55 +0200
EAPI=8

inherit octave

DESCRIPTION="JSON support by Matlab compatible (jsondecode / jsonencode) functions."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/gnu-octave/pkg-json/"

SRC_URI="
https://github.com/gnu-octave/pkg-json/archive/v1.0.0.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-5.1.0
	<sci-mathematics/octave-7.0.0"
DEPEND="${RDEPEND}"
