# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:08 +0200
EAPI=8

inherit octave

DESCRIPTION="Simple implementation of the Websockets protocol for GNU Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/gnu-octave/octave-websockets/"

SRC_URI="
https://github.com/gnu-octave/octave-websockets/archive/v0.1.0.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-3.2.0
	>=octave-packages/sockets-1.2.0"
DEPEND="${RDEPEND}"
