# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:51 +0200
EAPI=8

inherit octave

DESCRIPTION="Genetic optimization code."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/ga/ci/default/tree/"

SRC_URI="
https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/ga-0.10.1.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-3.4.0"
DEPEND="${RDEPEND}"
