# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:48:57 +0200
EAPI=8

inherit octave

DESCRIPTION="A NetCDF interface for Octave."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave/netcdf/ci/master/tree/"

SRC_URI="
	https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/netcdf-1.0.13.tar.gz -> ${P}.tar.gz"
RDEPEND="
	sci-libs/netcdf
	>=sci-mathematics/octave-3.8.0"
DEPEND="${RDEPEND}"
