# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:13 +0200
EAPI=8

inherit octave

DESCRIPTION="I/O routines to read and write FITS (Flexible Image Transport System) files."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://sourceforge.net/p/octave-cfitsio/code/ci/default/tree"

SRC_URI="
	https://downloads.sourceforge.net/project/octave-cfitsio/v0.0.1/octave-cfitsio-0.0.1.tar.gz -> ${P}.tar.gz"
RDEPEND="
	sci-libs/cfitsio
	>=sci-mathematics/octave-4.0.0"
DEPEND="${RDEPEND}"
