# Autogenerated by ./octave.sh on Sun, 13 Nov 2022 14:49:07 +0200
EAPI=8

inherit octave

DESCRIPTION="Bioinformatics tools."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/schloegl/octmat-bioinfo"

SRC_URI="
	https://github.com/schloegl/octmat-bioinfo/archive/refs/heads/master.tar.gz -> ${P}.tar.gz"
RDEPEND="
	>=sci-mathematics/octave-3.0.0"
DEPEND="${RDEPEND}"
