# Autogenerated by ./octave.sh on Tue, 08 Nov 2022 22:22:15 +0200
EAPI=8

inherit octave

DESCRIPTION="Bioinformatics tools."
LICENSE="GPL-3.0-or-later"
HOMEPAGE="https://github.com/schloegl/octmat-bioinfo"

SRC_URI="
https://github.com/schloegl/octmat-bioinfo/archive/refs/heads/master.tar.gz -> ${P}.tar.gz"
RESTRICT="mirror"
KEYWORDS="~amd64 ~x86"

RDEPEND="
	>=sci-mathematics/octave-3.0.0"
DEPEND="${RDEPEND}"
